[package]
name = "pulumi"
version = "0.1.0"
edition = "2024"
description = "Pulumi SDK for Rust — define cloud infrastructure as Rust code"
license = "Apache-2.0"
repository = "https://github.com/avtrujillo/pulumi-rs"

[features]
macros = ["dep:pulumi-macros"]

[dependencies]
pulumi-core = { path = "../pulumi-core" }
pulumi-macros = { path = "../pulumi-macros", optional = true }

[lib]
doctest = false
